#developed by Colin Averill, April 25, 2017
#this figure takes output generated by model_experiments/CN_by.clat_experiment_with_NUE.r
#varying C:N of inputs across clay
#clear R environment, load packages
rm(list=ls())
library(wesanderson)

#load model experiment data
no.clay <- readRDS('experiment_output/AV_no_clay.CN_NUE_model.rds')
lo.clay <- readRDS('experiment_output/AV_lo_clay.CN_NUE_model.rds')
hi.clay <- readRDS('experiment_output/AV_hi_clay.CN_NUE_model.rds')

#set figure output path
output.path <- 'figures/AV_Experiment 1. steady state CN by clay.png'

#begin figure.
png(filename=output.path,width=9,height=3.5,units='in',res=300)

par(mfrow=c(1,3), mai = c(0.5,0.3,0.3,0.3))
limy <- c(0,150)
#no clay panel
cols <- wes_palette("Zissou", 5)
plot(tot ~ CN, data = no.clay, ylim = limy, cex = 0, ylab = NA, xlab=NA)
lines(smooth.spline(no.clay$tot~no.clay$CN), lwd=3)
lines(smooth.spline(no.clay$C  ~no.clay$CN), lwd=2, col=cols[1])
lines(smooth.spline(no.clay$M  ~no.clay$CN), lwd=2, col=cols[3])
lines(smooth.spline(no.clay$B  ~no.clay$CN), lwd=2, col=cols[5])

#add labels
mtext('no sorption', line = 0.2)
mtext(expression(paste('mg C (g soil)'^'-1')), side=2, line = 2, las = 0, cex = 0.7)
mtext('input C:N', side = 1, line = 2.5, cex = 0.7)
mtext('a.', side =3, adj = 0.025, line = -1.25)

#legend
legend(30,145,c('total C','POM','MAOM','microbial'), lwd=c(3,2,2,2), col=c('black',cols[1],cols[3],cols[5]), bty='n', y.intersp = 1, x.intersp = 0.75, cex=1.2, seg.len=1)

#lo clay panel 
plot(tot ~ CN, data = lo.clay, ylim = limy, cex = 0, ylab = NA, xlab = NA)
lines(smooth.spline(lo.clay$tot~lo.clay$CN), lwd=3)
lines(smooth.spline(lo.clay$C  ~lo.clay$CN), lwd=2, col=cols[1])
lines(smooth.spline(lo.clay$M  ~lo.clay$CN), lwd=2, col=cols[3])
lines(smooth.spline(lo.clay$B  ~lo.clay$CN), lwd=2, col=cols[5])
#add labels
mtext('low sorption', line = 0.2)
mtext(expression(paste('mg C (g soil)'^'-1')), side=2, line = 2, las = 0, cex = 0.7)
mtext('input C:N', side = 1, line = 2.5, cex = 0.7)
mtext('b.', side =3, adj = 0.025, line = -1.25)

#hi clay panel 
plot(tot ~ CN, data = hi.clay, ylim = limy, cex = 0, ylab = NA, xlab = NA)
lines(smooth.spline(hi.clay$tot~hi.clay$CN), lwd=3)
lines(smooth.spline(hi.clay$C  ~hi.clay$CN), lwd=2, col=cols[1])
lines(smooth.spline(hi.clay$M  ~hi.clay$CN), lwd=2, col=cols[3])
lines(smooth.spline(hi.clay$B  ~hi.clay$CN), lwd=2, col=cols[5])
#add labels
mtext('high sorption', line = 0.2)
mtext(expression(paste('mg C (g soil)'^'-1')), side=2, line = 2, las = 0, cex = 0.7)
mtext('input C:N', side = 1, line = 2.5, cex = 0.7)
mtext('c.', side =3, adj = 0.025, line = -1.25)

#inset panel 1
#par(fig=c(.05, .125, .620, .770), new = T, mar = c(0,0,0,0))
#plot(no.clay$B ~ no.clay$CN, axes=T, ylim = c(0,10), cex = 0, xlab=NA, ylab=NA, xaxt='n', yaxt='n')
#lines(smooth.spline(no.clay$B  ~no.clay$CN), lwd=2, col=cols[5])
#mtext('biomass', side = 2, line = 0, cex = 0.5)
#mtext('input C:N', side = 1, line = 0, cex = 0.5)

#inset panel 2
#par(fig=c(.39, .465, .620, .770), new = T, mar = c(0,0,0,0))
#plot(lo.clay$B ~ lo.clay$CN, axes=T, ylim = c(0,10), cex = 0, xlab=NA, ylab=NA, xaxt='n', yaxt='n')
#lines(smooth.spline(lo.clay$B  ~lo.clay$CN), lwd=2, col=cols[5])
#mtext('biomass', side = 2, line = 0, cex = 0.5)
#mtext('input C:N', side = 1, line = 0, cex = 0.5)

#inset panel 3
#par(fig=c(.72, .795, .620, .770), new = T, mar = c(0,0,0,0))
#plot(hi.clay$B ~ hi.clay$CN, axes=T, ylim = c(0,10), cex = 0, xlab=NA, ylab=NA, xaxt='n', yaxt='n')
#lines(smooth.spline(hi.clay$B  ~hi.clay$CN), lwd=2, col=cols[5])
#mtext('biomass', side = 2, line = 0, cex = 0.5)
#mtext('input C:N', side = 1, line = 0, cex = 0.5)

dev.off()