#this figure takes output generated by model_experiments/C-only_clay.by.CUE_experiment.r
#varying CUE across clay
#clear R environment, load packages
rm(list=ls())
library(wesanderson)

no.clay <- readRDS('experiment_output/no_clay.C_only.rds')
lo.clay <- readRDS('experiment_output/lo_clay.C_only.rds')
hi.clay <- readRDS('experiment_output/hi_clay.C_only.rds')


#setup save destination
#save dimensions, destination
png(filename='figures/Experiment_1_results.png',width=8,height=3.5,units='in',res=300)

par(mfrow=c(1,3))
#no clay panel
cols <- wes_palette("Zissou", 5)
plot(tot ~ CUE, data = no.clay, ylim = c(0,100), cex = 0, ylab = 'mg C per g soil')
lines(smooth.spline(no.clay$tot~no.clay$CUE), lwd=2)
lines(smooth.spline(no.clay$C  ~no.clay$CUE), lwd=2, col=cols[1])
lines(smooth.spline(no.clay$M  ~no.clay$CUE), lwd=2, col=cols[3])
lines(smooth.spline(no.clay$B  ~no.clay$CUE), lwd=2, col=cols[5])
mtext('no clay', line = 0.2)

#legend
legend(.35, 95,c('total C','POM','MAOM','microbial'), lwd=2, col=c('black',cols[1],cols[3],cols[5]), bty='n', y.intersp = 1, x.intersp = 0.75, cex=1.2, seg.len=1)


#lo clay panel 
plot(tot ~ CUE, data = lo.clay, ylim = c(0,100), cex = 0, ylab = 'mg C per g soil')
lines(smooth.spline(lo.clay$tot~lo.clay$CUE), lwd=2)
lines(smooth.spline(lo.clay$C  ~lo.clay$CUE), lwd=2, col=cols[1])
lines(smooth.spline(lo.clay$M  ~lo.clay$CUE), lwd=2, col=cols[3])
lines(smooth.spline(lo.clay$B  ~lo.clay$CUE), lwd=2, col=cols[5])
mtext('low clay', line = 0.2)

#hi clay panel 
plot(tot ~ CUE, data = hi.clay, ylim = c(0,100), cex = 0, ylab = 'mg C per g soil')
lines(smooth.spline(hi.clay$tot~hi.clay$CUE), lwd=2)
lines(smooth.spline(hi.clay$C  ~hi.clay$CUE), lwd=2, col=cols[1])
lines(smooth.spline(hi.clay$M  ~hi.clay$CUE), lwd=2, col=cols[3])
lines(smooth.spline(hi.clay$B  ~hi.clay$CUE), lwd=2, col=cols[5])
mtext('high clay', line = 0.2)

dev.off()